### ISSUE TITLE
Sometimes randomly crashes on load, mixin fault with Java 15

### ISSUE THREAD

**Issue by NighthowlerStudios** [LudoCrypt/Music-Duration-Reducer#3]
Java 15 was being used at the time

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.ForgeConfigSpec$BooleanValue.get()" because "net.ludocrypt.musicdr.config.MusicConfig.divide" is null
	at net.minecraft.client.audio.BackgroundMusicSelector.handler$zzk000$musicDr_getMaxDelay(SourceFile:531) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:musicdr.mixins.json:MusicMixin,pl:mixin:A}
	at net.minecraft.client.audio.BackgroundMusicSelector.func_232666_c_(SourceFile:35) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:musicdr.mixins.json:MusicMixin,pl:mixin:A}
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile:41) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MusicTickerMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1490) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}

**Comment by Stormalisk** [comment]
I'm getting this as well with Java 17

**Comment by LudoCrypt** [comment]
weird, ill look into this

**Comment by Stormalisk** [comment]
Using Java 17 here, but it may be related to when I get the same crash.

It seems to be something when I install a mod that needs a different forge version.

Instead of getting the error screen from that mod, stating that I need a forge update, it just crashes with the null report.
